port:  4000
markdown: kramdown
name: Chi Hack Night
url: http://chihacknight.org
title: Chi Hack Night
description: "Chicago's weekly event to build, share, and learn about civic tech."
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']